version: '3'
services:
  db:
    container_name: db_container
    build: ./build_db
    restart: always
    # ports:
    #   - "13316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  scraper:
    container_name: scraper_container
    tty: true
    # ports:
    #   - "10180:80"
    build: ./build_scraper
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - db

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: ./build_api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./api:/app  # apiディレクトリをマウント
    ports:
      - "5110:8000"  # ホストの5110番ポートをコンテナの8000番ポートにマッピング
    networks:
      - backend
    depends_on:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "18081:80"  # phpMyAdmin をホストの8080ポートで公開
    environment:
      PMA_HOST: db  # MariaDBのサービス名（コンテナ名ではない）を指定
      PMA_USER: ${MYSQL_USER}  # 環境変数からMariaDBのユーザー名を取得
      PMA_PASSWORD: ${MYSQL_PASSWORD}  # 環境変数からパスワードを取得
    networks:
      - backend


networks:
  backend:

volumes:
  db_data:
